services:
  app:
    build:
      context: ./Back-End
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - restaurante-net

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurante
    networks:
      - restaurante-net

  frontend:
    build:
      context: ./Front-End
    ports:
      - "5173:80"
    networks:
      - restaurante-net
    depends_on:
      - app

networks:
  restaurante-net:
    driver: bridge
