version: "3.9"

services:
  app:
    build:
      context: ./Back-End
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: restaurante
      DB_USERNAME: root
      DB_PASSWORD: root
      APP_ENV: production
      APP_KEY: base64:PLACEHOLDER_APP_KEY
      APP_URL: http://localhost:8000
    networks:
      - restaurante-net

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurante
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - restaurante-net

  frontend:
    build:
      context: ./Front-End
    ports:
      - "5173:80"
    depends_on:
      - app
    networks:
      - restaurante-net

volumes:
  dbdata:

networks:
  restaurante-net:
    driver: bridge
